#!/bin/sh

VERSION="${VERSION:-latest}"

ARCH="${ARCH:-$(uname -m)}"
if [ ${ARCH} = "x86_64" ] ; then
    ARCH="amd64"
fi
if [ ${ARCH} = "armv7l" ] ; then
    ARCH="armhf"
fi

USERID="${USERID:-$(id -u)}"

docker run -u ${USERID} -t -i --rm -v $(pwd):/build \
    --privileged=true \
    -v ${HOME}/.snap:/home/.snap \
    -v ${HOME}/.local/share/snapcraft:/home/.local/share/snapcraft \
    -v ${HOME}/.cache/snapcraft:/home/.cache/snapcraft \
    -v ${HOME}/.config/snapcraft:/home/.config/snapcraft \
    snapcraft/xenial-${ARCH}:${VERSION} $@
